CREATE TABLE CLAIM (
    CLAIM_ID            NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CLAIM_NUMBER         VARCHAR2(30) UNIQUE NOT NULL,
    POLICY_ID            NUMBER NOT NULL REFERENCES POLICY(POLICY_ID),
    CUSTOMER_ID           NUMBER NOT NULL REFERENCES CUSTOMER(CUSTOMER_ID),
    INCIDENT_DATE         DATE,
    DESCRIPTION           VARCHAR2(2000),
    CLAIM_AMOUNT          NUMBER(10,3) NOT NULL,
    IMAGE_PATH            VARCHAR2(500),
    CLAIM_STATUS          VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    -- STP_APPROVED | PENDING | APPROVED | DECLINED
    ADJUSTER_NOTE          VARCHAR2(2000),
    APPROVED_AMOUNT        NUMBER(10,3),
    SUBMITTED_AT           TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DECIDED_AT             TIMESTAMP
);

CREATE SEQUENCE CLAIM_SEQ START WITH 1 INCREMENT BY 1;
SELECT * FROM CLAIM ;

  DELETE FROM CLAIM;
  COMMIT;