CREATE TABLE QUOTES (
    quote_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quote_number   VARCHAR2(30) NOT NULL,
    customer_id    NUMBER NOT NULL,
    vehicle_id     NUMBER NOT NULL,
    product_code   VARCHAR2(50),
    status         VARCHAR2(20),
    valid_from     DATE,
    valid_to       DATE,
    created_at     TIMESTAMP,

    CONSTRAINT fk_quote_customer
        FOREIGN KEY (customer_id)
        REFERENCES CUSTOMER(customer_id),

    CONSTRAINT fk_quote_vehicle
        FOREIGN KEY (vehicle_id)
        REFERENCES VEHICLES(vehicle_id)
);
INSERT ALL

    INTO QUOTES
    (quote_number, customer_id, vehicle_id, product_code,
     status, valid_from, valid_to, created_at)
    VALUES
    ('QT-2026-0001', 1, 1, 'MOTOR-COMP',
     'ACTIVE',
     TO_DATE('2026-08-28', 'YYYY-MM-DD'),
     TO_DATE('2026-09-04', 'YYYY-MM-DD'),
     TO_TIMESTAMP('2026-08-28 10:15:00', 'YYYY-MM-DD HH24:MI:SS'))

    INTO QUOTES
    (quote_number, customer_id, vehicle_id, product_code,
     status, valid_from, valid_to, created_at)
    VALUES
    ('QT-2026-0002', 2, 2, 'MOTOR-TP',
     'EXPIRED',
     TO_DATE('2026-07-10', 'YYYY-MM-DD'),
     TO_DATE('2026-07-17', 'YYYY-MM-DD'),
     TO_TIMESTAMP('2026-07-10 14:30:00', 'YYYY-MM-DD HH24:MI:SS'))

    INTO QUOTES
    (quote_number, customer_id, vehicle_id, product_code,
     status, valid_from, valid_to, created_at)
    VALUES
    ('QT-2026-0003', 3, 3, 'MOTOR-COMP',
     'ACTIVE',
     TO_DATE('2026-08-25', 'YYYY-MM-DD'),
     TO_DATE('2026-09-01', 'YYYY-MM-DD'),
     TO_TIMESTAMP('2026-08-25 09:45:00', 'YYYY-MM-DD HH24:MI:SS'))

    INTO QUOTES
    (quote_number, customer_id, vehicle_id, product_code,
     status, valid_from, valid_to, created_at)
    VALUES
    ('QT-2026-0004', 4, 4, 'MOTOR-TP',
     'ACCEPTED',
     TO_DATE('2026-08-20', 'YYYY-MM-DD'),
     TO_DATE('2026-08-27', 'YYYY-MM-DD'),
     TO_TIMESTAMP('2026-08-20 16:20:00', 'YYYY-MM-DD HH24:MI:SS'))

    INTO QUOTES
    (quote_number, customer_id, vehicle_id, product_code,
     status, valid_from, valid_to, created_at)
    VALUES
    ('QT-2026-0005', 5, 5, 'MOTOR-COMP',
     'DRAFT',
     TO_DATE('2026-08-28', 'YYYY-MM-DD'),
     TO_DATE('2026-09-04', 'YYYY-MM-DD'),
     TO_TIMESTAMP('2026-08-28 11:05:00', 'YYYY-MM-DD HH24:MI:SS'))

SELECT 1 FROM DUAL;

COMMIT;

SELECT * FROM QUOTES;
