CREATE TABLE CHAT_RATINGS (
    RATING_ID      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CUSTOMER_ID    NUMBER,
    SESSION_ID     VARCHAR2(100) NOT NULL,
    RATING         NUMBER(1) NOT NULL,
    FEEDBACK       CLOB,
    LANGUAGE       VARCHAR2(5) DEFAULT 'en',
    CREATED_AT     TIMESTAMP DEFAULT SYSTIMESTAMP,

    CONSTRAINT FK_CHAT_RATING_CUSTOMER
        FOREIGN KEY (CUSTOMER_ID)
        REFERENCES CUSTOMER(CUSTOMER_ID),

    CONSTRAINT CHK_CHAT_RATING_VALUE
        CHECK (RATING BETWEEN 1 AND 5)
);

CREATE INDEX IDX_CHAT_RATINGS_CUSTOMER
ON CHAT_RATINGS (CUSTOMER_ID);

CREATE INDEX IDX_CHAT_RATINGS_SESSION
ON CHAT_RATINGS (SESSION_ID);


ALTER TABLE CHAT_RATINGS MODIFY CUSTOMER_ID NULL;

SELECT *
FROM CHAT_RATINGS
ORDER BY CREATED_AT DESC;

SELECT *
FROM CHAT_RATINGS
WHERE CUSTOMER_ID = 1
ORDER BY CREATED_AT DESC;

SELECT *
FROM CHAT_RATINGS
WHERE SESSION_ID = 'sess_xxxxx'
ORDER BY CREATED_AT DESC;

SELECT table_name FROM user_tables WHERE table_name = 'CHAT_RATINGS';

SELECT CUSTOMER_ID FROM CUSTOMER WHERE CUSTOMER_ID = 1;
SELECT * FROM CHAT_RATINGS;
SELECT
    USER AS CURRENT_USER
FROM DUAL;

SELECT
    OWNER,
    TABLE_NAME,
    COLUMN_NAME,
    DATA_TYPE,
    DATA_LENGTH
FROM ALL_TAB_COLUMNS
WHERE TABLE_NAME = 'CHAT_RATINGS'
ORDER BY OWNER, COLUMN_ID;
DESC CHAT_RATINGS;
ALTER TABLE CHAT_RATINGS
ADD FOLLOW_UP_STATUS VARCHAR2(20) DEFAULT 'NOT_REQUIRED' NOT NULL;
SELECT * FROM CHAT_RATINGS;