-- CREATE TABLE FAQ (
--     FAQ_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     CATEGORY VARCHAR2(30),
--     QUESTION VARCHAR2(300),
--     ANSWER VARCHAR2(1000)
-- );
-- INSERT INTO FAQ (CATEGORY, QUESTION, ANSWER)
-- VALUES ('Health', 'What is health insurance?',
-- 'Health insurance helps cover medical expenses such as hospitalization, surgery, and treatments.');

-- INSERT INTO FAQ (CATEGORY, QUESTION, ANSWER)
-- VALUES ('Health', 'Does health insurance cover surgery?',
-- 'Yes, most health insurance plans cover surgery as per the policy terms.');

-- INSERT INTO FAQ (CATEGORY, QUESTION, ANSWER)
-- VALUES ('Vehicle', 'How do I claim vehicle insurance?',
-- 'Inform the insurer, submit the required documents, and complete the claim process.');

-- INSERT INTO FAQ (CATEGORY, QUESTION, ANSWER)
-- VALUES ('Vehicle', 'Does vehicle insurance cover accidents?',
-- 'Yes, comprehensive vehicle insurance generally covers accident damages.');

-- INSERT INTO FAQ (CATEGORY, QUESTION, ANSWER)
-- VALUES ('Life', 'What is life insurance?',
-- 'Life insurance provides financial support to the nominee in case of the policyholder''s death.');

-- INSERT INTO FAQ (CATEGORY, QUESTION, ANSWER)
-- VALUES ('Life', 'Can I change my nominee?',
-- 'Yes, you can update your nominee by submitting a request to the insurance company.');

-- INSERT INTO FAQ (CATEGORY, QUESTION, ANSWER)
-- VALUES ('Travel', 'What does travel insurance cover?',
-- 'Travel insurance covers trip cancellation, baggage loss, medical emergencies, and travel delays.');

-- INSERT INTO FAQ (CATEGORY, QUESTION, ANSWER)
-- VALUES ('Travel', 'Does travel insurance cover lost baggage?',
-- 'Yes, many travel insurance plans provide compensation for lost baggage.');

-- INSERT INTO FAQ (CATEGORY, QUESTION, ANSWER)
-- VALUES ('General', 'How can I renew my policy?',
-- 'You can renew your policy online through the insurance portal or by contacting customer support.');

-- INSERT INTO FAQ (CATEGORY, QUESTION, ANSWER)
-- VALUES ('General', 'How do I contact customer support?',
-- 'You can contact customer support through phone, email, or the official website.');

-- COMMIT;
SELECT * FROM FAQ;