create table customer (
   customer_id   number generated by default as identity primary key,
   customer_name varchar2(100) not null,
   email         varchar2(100),
   phone         varchar2(15),
   city          varchar2(50)
);
INSERT INTO CUSTOMER (CUSTOMER_NAME, EMAIL, PHONE, CITY)
VALUES ('Rahul Sharma', 'rahul@gmail.com', '9876543210', 'Chennai');

INSERT INTO CUSTOMER (CUSTOMER_NAME, EMAIL, PHONE, CITY)
VALUES ('Priya Kumar', 'priya@gmail.com', '9876543211', 'Bangalore');

INSERT INTO CUSTOMER (CUSTOMER_NAME, EMAIL, PHONE, CITY)
VALUES ('Arjun Singh', 'arjun@gmail.com', '9876543212', 'Hyderabad');

INSERT INTO CUSTOMER (CUSTOMER_NAME, EMAIL, PHONE, CITY)
VALUES ('Sneha Patel', 'sneha@gmail.com', '9876543213', 'Mumbai');

INSERT INTO CUSTOMER (CUSTOMER_NAME, EMAIL, PHONE, CITY)
VALUES ('Vikram Rao', 'vikram@gmail.com', '9876543214', 'Delhi');

COMMIT;
SELECT * FROM CUSTOMER;

DELETE FROM CUSTOMER WHERE CUSTOMER_ID > 5;
COMMIT;

TRUNCATE TABLE CUSTOMER;
ALTER TABLE CUSTOMER MODIFY(CUSTOMER_ID GENERATED BY DEFAULT AS IDENTITY (START WITH 1));

DELETE FROM CUSTOMER WHERE CUSTOMER_ID = 11;
COMMIT;


