CREATE TABLE POLICY_DOCUMENT (
    DOC_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    POLICY_TYPE VARCHAR2(30),
    TITLE VARCHAR2(100),
    CONTENT CLOB
);
INSERT INTO POLICY_DOCUMENT (POLICY_TYPE, TITLE, CONTENT)
VALUES (
'Health',
'Health Insurance Coverage',
'Health insurance covers hospitalization expenses, ICU charges, surgeries, ambulance charges, pre and post hospitalization expenses, and daycare procedures. Pre-existing diseases are covered only after the waiting period mentioned in the policy.'
);
INSERT INTO POLICY_DOCUMENT (POLICY_TYPE, TITLE, CONTENT)
VALUES (
'Vehicle',
'Vehicle Insurance Coverage',
'Vehicle insurance provides financial protection against accidents, theft, fire, natural disasters, and third-party liabilities. Claims require valid vehicle documents and a driving license.'
);
INSERT INTO POLICY_DOCUMENT (POLICY_TYPE, TITLE, CONTENT)
VALUES (
'Life',
'Life Insurance Benefits',
'Life insurance provides financial protection to the nominee in case of the policyholder''s death. Some plans also offer maturity benefits and tax benefits.'
);
INSERT INTO POLICY_DOCUMENT (POLICY_TYPE, TITLE, CONTENT)
VALUES (
'Travel',
'Travel Insurance Coverage',
'Travel insurance covers trip cancellation, baggage loss, passport loss, medical emergencies abroad, emergency evacuation, and travel delays. It does not cover losses caused by illegal activities.'
);
INSERT INTO POLICY_DOCUMENT (POLICY_TYPE, TITLE, CONTENT)
VALUES (
'Home',
'Home Insurance Coverage',
'Home insurance covers damage caused by fire, floods, earthquakes, theft, and certain natural disasters. It does not cover intentional damage or normal wear and tear.'
);

COMMIT;
SELECT * FROM POLICY_DOCUMENT;