CREATE TABLE CHAT_HISTORY (
  HISTORY_ID     NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CUSTOMER_ID    NUMBER NOT NULL,
  SESSION_ID     VARCHAR2(50) NOT NULL,
  ROLE           VARCHAR2(10) NOT NULL, -- 'user' | 'bot'
  CONTENT        CLOB NOT NULL,
  LANGUAGE       VARCHAR2(5) DEFAULT 'en',
  CREATED_AT     TIMESTAMP DEFAULT SYSTIMESTAMP,
  CONSTRAINT FK_CHAT_HISTORY_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);

CREATE INDEX IDX_CHAT_HISTORY_CUST_SESSION ON CHAT_HISTORY (CUSTOMER_ID, SESSION_ID);

SELECT CUSTOMER_ID, SESSION_ID, ROLE, LANGUAGE, CREATED_AT
FROM CHAT_HISTORY
ORDER BY CREATED_AT DESC;

SELECT
    HISTORY_ID,
    CUSTOMER_ID,
    SESSION_ID,
    ROLE,
    CONTENT,
    LANGUAGE,
    CREATED_AT
FROM CHAT_HISTORY
ORDER BY CREATED_AT ASC;